server:
  port: 8081

spring:
  application:
    name: sledgehammer-order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: u7UIOw1dLKMZ  # 使用你安装时生成的密码
