spring:
  application:
    name: sledgehammer-user-service
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:9TVlQPhvwgXU}
      config:
        server-addr: 127.0.0.1:8848
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:9TVlQPhvwgXU}
        file-extension: yml
  config:
    import:
      - optional:nacos:${spring.application.name}-dev.yml

